import { execFile } from "node:child_process";
import { realpathSync } from "node:fs";
import { basename, dirname, relative, resolve } from "node:path";
import { promisify } from "node:util";
import type { ChangedFile, CommitEvent, DiffFetcher } from "../core/types.js";

const execFileAsync = promisify(execFile);
const emptyTreeSha = "4b825dc642cb6eb9a060e54bf8d69288fbee4904";

type InstallPostCommitHookOptions = {
  command?: string;
  fallbackScriptPath?: string;
  ref?: string;
  outDir?: string;
  storePath?: string;
  adapter?: string;
};

export async function createLocalGitCommitEvent(
  repoPath: string,
  ref = "HEAD"
): Promise<CommitEvent> {
  const repoRoot = await resolveGitRepoRoot(repoPath);
  const afterSha = await git(repoRoot, ["rev-parse", ref]);
  const beforeSha = await parentSha(repoRoot, afterSha);
  const branch = await currentBranch(repoRoot);
  const message = await git(repoRoot, ["log", "-1", "--format=%B", afterSha]);
  const authorName = await git(repoRoot, ["log", "-1", "--format=%an", afterSha]);
  const authorEmail = await git(repoRoot, ["log", "-1", "--format=%ae", afterSha]);
  const occurredAt = await git(repoRoot, ["log", "-1", "--format=%cI", afterSha]);

  return {
    provider: "local_git",
    repo: basename(repoRoot),
    branch,
    beforeSha,
    afterSha,
    commitUrl: `local:${repoRoot}@${afterSha}`,
    authorName,
    authorEmail,
    message,
    occurredAt
  };
}

export class LocalGitDiffFetcher implements DiffFetcher {
  constructor(private readonly repoPath: string) {}

  async fetch(event: CommitEvent): Promise<ChangedFile[]> {
    const repoRoot = await resolveGitRepoRoot(this.repoPath);
    const nameStatus = await git(repoRoot, [
      "diff-tree",
      "--root",
      "--no-commit-id",
      "--name-status",
      "-r",
      "-M",
      event.afterSha
    ]);

    if (!nameStatus) {
      return [];
    }

    const files = await Promise.all(
      nameStatus.split("\n").map(async (line) => {
        const parts = line.split("\t");
        const statusCode = parts[0];
        const path = statusCode.startsWith("R") ? parts[2] : parts[1];
        const stats = await fileStats(repoRoot, event.beforeSha, event.afterSha, path);
        const patch = await filePatch(repoRoot, event.beforeSha, event.afterSha, path);

        return {
          path,
          status: normalizeStatus(statusCode),
          additions: stats.additions,
          deletions: stats.deletions,
          patch
        };
      })
    );

    return files;
  }
}

export async function resolveGitRepoRoot(repoPath: string): Promise<string> {
  return git(repoPath, ["rev-parse", "--show-toplevel"]);
}

export async function installPostCommitHook(
  repoPath: string,
  options: InstallPostCommitHookOptions
): Promise<string> {
  const { mkdir, writeFile, chmod } = await import("node:fs/promises");
  const repoRoot = await resolveGitRepoRoot(repoPath);
  const gitDir = await git(repoRoot, ["rev-parse", "--git-dir"]);
  const hookPath = resolve(repoRoot, gitDir, "hooks", "post-commit");
  const ref = options.ref ?? "HEAD";
  const outDir = options.outDir ?? "docs";
  const storePath = options.storePath ?? ".run-store/runs.json";
  const adapterArg = options.adapter ? ` --adapter "${options.adapter}"` : "";
  const fallbackCommand = buildHookFallbackCommand(repoRoot, options);
  const hook = [
    "#!/bin/sh",
    "# Generated by commit-doc-agent.",
    'repo_root="$(git rev-parse --show-toplevel 2>/dev/null)"',
    '[ -n "$repo_root" ] || exit 0',
    'cd "$repo_root" || exit 0',
    "run_commit_doc_agent() {",
    '  if [ -x "./node_modules/.bin/commit-doc-agent" ]; then',
    '    "./node_modules/.bin/commit-doc-agent" "$@"',
    "    return",
    "  fi",
    "  if command -v commit-doc-agent >/dev/null 2>&1; then",
    '    commit-doc-agent "$@"',
    "    return",
    "  fi",
    `  ${fallbackCommand} "$@"`,
    "}",
    `run_commit_doc_agent local --repo "." --ref "${ref}" --out "${outDir}" --store "${storePath}"${adapterArg} || true`,
    ""
  ].join("\n");

  await mkdir(resolve(repoRoot, gitDir, "hooks"), { recursive: true });
  await writeFile(hookPath, hook, "utf8");
  await chmod(hookPath, 0o755);

  return hookPath;
}

function buildHookFallbackCommand(
  repoRoot: string,
  options: InstallPostCommitHookOptions
): string {
  if (options.fallbackScriptPath) {
    const relativePath = toHookRelativePath(repoRoot, options.fallbackScriptPath);

    return `node "${relativePath}"`;
  }

  if (options.command) {
    return options.command;
  }

  throw new Error("installPostCommitHook requires a command or fallbackScriptPath.");
}

function toHookRelativePath(repoRoot: string, targetPath: string): string {
  const normalizedRepoRoot = normalizeHookPath(repoRoot);
  const normalizedTargetPath = normalizeHookPath(targetPath);
  const relativePath = relative(normalizedRepoRoot, normalizedTargetPath).replace(/\\/g, "/");

  if (relativePath.startsWith(".") || relativePath.startsWith("/")) {
    return relativePath;
  }

  return `./${relativePath}`;
}

function normalizeHookPath(path: string): string {
  const resolvedPath = resolve(path);

  try {
    return realpathSync(resolvedPath);
  } catch {
    let currentPath = dirname(resolvedPath);

    while (currentPath !== dirname(currentPath)) {
      try {
        const realParent = realpathSync(currentPath);
        const relativeTail = relative(currentPath, resolvedPath);

        return resolve(realParent, relativeTail);
      } catch {
        currentPath = dirname(currentPath);
      }
    }

    return resolvedPath;
  }
}

async function parentSha(repoPath: string, sha: string): Promise<string> {
  try {
    return await git(repoPath, ["rev-parse", `${sha}^`]);
  } catch {
    return emptyTreeSha;
  }
}

async function currentBranch(repoPath: string): Promise<string> {
  try {
    return await git(repoPath, ["branch", "--show-current"]);
  } catch {
    return "detached";
  }
}

async function fileStats(
  repoPath: string,
  beforeSha: string,
  afterSha: string,
  path: string
): Promise<{ additions: number; deletions: number }> {
  const output = await git(repoPath, ["diff", "--numstat", beforeSha, afterSha, "--", path]);
  const [additions = "0", deletions = "0"] = output.split("\t");

  return {
    additions: parseIntStat(additions),
    deletions: parseIntStat(deletions)
  };
}

async function filePatch(
  repoPath: string,
  beforeSha: string,
  afterSha: string,
  path: string
): Promise<string | undefined> {
  const output = await git(repoPath, ["diff", "--patch", beforeSha, afterSha, "--", path]);

  return output || undefined;
}

async function git(repoPath: string, args: string[]): Promise<string> {
  const { stdout } = await execFileAsync("git", ["-C", resolve(repoPath), ...args], {
    maxBuffer: 10 * 1024 * 1024
  });

  return stdout.trim();
}

function normalizeStatus(statusCode: string): ChangedFile["status"] {
  if (statusCode === "A") {
    return "added";
  }

  if (statusCode === "D") {
    return "removed";
  }

  if (statusCode.startsWith("R")) {
    return "renamed";
  }

  return "modified";
}

function parseIntStat(value: string): number {
  if (value === "-") {
    return 0;
  }

  return Number.parseInt(value, 10) || 0;
}
